apiVersion: v1
kind: Service
metadata:
  name: pyapp-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  selector:
    app: pyapp
  ports:
  - port: 80
    targetPort: 8080

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pyapp
  template:
    metadata:
      labels:
        app: pyapp
    spec:
      containers:
      - name: pyapp-cont
        image: mnevadom/pyk8s:v6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts: 
          - name: config-vol
            mountPath: /properties/
          - name: secrets-vol
            mountPath: /secretos/
      volumes: 
        - name: config-vol
          configMap: 
            name: config-app
        - name: secrets-vol
          secret: 
            secretName: db-user-pass

